<%@ Page Title="" Language="C#" MasterPageFile="~/AdminSite.Master" AutoEventWireup="true" ValidateRequest="false" CodeBehind="AdminLearners.aspx.cs" Inherits="VisualMech.WebForm7" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Learner Management</h1>
    </div>

    <hr class="thicker-line-10"/>


    <div class="row overflow-auto d-grid">
            <asp:GridView runat="server" ID="LearnerGridView" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" DataKeyNames="user_id"
                 OnRowCancelingEdit="LearnerGridView_RowCancelingEdit" OnRowEditing="LearnerGridView_RowEditing" AutoGenerateColumns="false"
                 OnRowUpdating="LearnerGridView_RowUpdating" OnRowDataBound="LearnerGridView_RowDataBound" CssClass="gridview-scrollable mx-auto"
                 OnRowDeleting="LearnerGridView_RowDeleting" >
            <Columns>
                <asp:TemplateField HeaderText="User ID">
                    <ItemTemplate>
                        <asp:Label ID="lblUserID" runat="server" Text='<%# Eval("user_id") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Username">
                    <ItemTemplate>
                        <asp:Label ID="lblUsername" runat="server" Text='<%# Eval("username") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="txtUsername" runat="server" Text='<%# Bind("username") %>'></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Email">
                    <ItemTemplate>
                        <asp:Label ID="lblEmail" runat="server" Text='<%# Eval("email") %>'></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="txtEmail" runat="server" Text='<%# Bind("email") %>'></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>
        
            </Columns>
            
            
            </asp:GridView>


            
        </div>

        <script type="text/javascript">
        function confirmDelete(cardID) {
            return confirm("Are you sure you want to delete this record?");
        }
        </script>
</asp:Content>
